import {
  Flame,
  LineChart,
  Radar,
  Send,
  CalendarDays,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

export type NavItem = {
  title: string;
  href: string;
  icon: LucideIcon;
  description: string;
};

export const navItems: NavItem[] = [
  {
    title: "Hook Vault",
    href: "/hook-vault",
    icon: Sparkles,
    description: "Every viral hook you've saved, transcribed and templatized",
  },
  {
    title: "Analytics",
    href: "/analytics",
    icon: LineChart,
    description: "Views, saves, follows, and this week's heaters",
  },
  {
    title: "Competitor Tracker",
    href: "/competitor-tracker",
    icon: Radar,
    description: "Top reels from creators you track, scraped weekly",
  },
  {
    title: "Scheduler",
    href: "/scheduler",
    icon: Send,
    description: "One-click multi-platform scheduling with autogenerated captions",
  },
  {
    title: "Content Calendar",
    href: "/content-calendar",
    icon: CalendarDays,
    description: "Auto-filled by /script with hooks and angles",
  },
  {
    title: "What's Trending",
    href: "/trending",
    icon: Flame,
    description: "AI news from 12 sources, tagged for hook potential",
  },
];
